// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYuEdCDusqfvYpJ3F4l3j7FROxe03jjPQ',
    appId: '1:566475001303:web:1281e0a5b69a6dc58b8f92',
    messagingSenderId: '566475001303',
    projectId: 'campusmatch-2991a',
    authDomain: 'campusmatch-2991a.firebaseapp.com',
    databaseURL: 'https://campusmatch-2991a-default-rtdb.firebaseio.com',
    storageBucket: 'campusmatch-2991a.firebasestorage.app',
    measurementId: 'G-68V6ZDLEH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HXeSQtmJDyiB80qY2D_g_dugOuIMi1Q',
    appId: '1:566475001303:android:2371d6ec50b2178f8b8f92',
    messagingSenderId: '566475001303',
    projectId: 'campusmatch-2991a',
    databaseURL: 'https://campusmatch-2991a-default-rtdb.firebaseio.com',
    storageBucket: 'campusmatch-2991a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-o-f4Q0Qq4hGS_tHoVyAc_Y87LL9XohU',
    appId: '1:566475001303:ios:402ad614ec58193c8b8f92',
    messagingSenderId: '566475001303',
    projectId: 'campusmatch-2991a',
    databaseURL: 'https://campusmatch-2991a-default-rtdb.firebaseio.com',
    storageBucket: 'campusmatch-2991a.firebasestorage.app',
    iosBundleId: 'com.example.campusMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-o-f4Q0Qq4hGS_tHoVyAc_Y87LL9XohU',
    appId: '1:566475001303:ios:402ad614ec58193c8b8f92',
    messagingSenderId: '566475001303',
    projectId: 'campusmatch-2991a',
    databaseURL: 'https://campusmatch-2991a-default-rtdb.firebaseio.com',
    storageBucket: 'campusmatch-2991a.firebasestorage.app',
    iosBundleId: 'com.example.campusMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYuEdCDusqfvYpJ3F4l3j7FROxe03jjPQ',
    appId: '1:566475001303:web:8be8e03ef99d10188b8f92',
    messagingSenderId: '566475001303',
    projectId: 'campusmatch-2991a',
    authDomain: 'campusmatch-2991a.firebaseapp.com',
    databaseURL: 'https://campusmatch-2991a-default-rtdb.firebaseio.com',
    storageBucket: 'campusmatch-2991a.firebasestorage.app',
    measurementId: 'G-VQBD5W7L0E',
  );
}
